In [1]:
import numpy as np

In [2]:
x = np.array([1,2,3])

In [3]:
a = np.eye(3)

In [4]:
np.linalg.det(a)

1.0

In [5]:
np.linspace(3,27,9)

array([ 3.,  6.,  9., 12., 15., 18., 21., 24., 27.])

In [6]:
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [7]:
np.arange(0,11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [10]:
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [11]:
np.full((5,2),1)

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1]])

In [15]:
x = np.identity((3))

In [16]:
np.linalg.det(x)

1.0

In [18]:
with open("index.csv",'w') as f :
    for i in range(100):
        f.write(str(i) + "," + str(i**2) + "\n")

In [19]:
y = np.genfromtxt("index.csv",delimiter=',')

In [20]:
y

array([[0.000e+00, 0.000e+00],
       [1.000e+00, 1.000e+00],
       [2.000e+00, 4.000e+00],
       [3.000e+00, 9.000e+00],
       [4.000e+00, 1.600e+01],
       [5.000e+00, 2.500e+01],
       [6.000e+00, 3.600e+01],
       [7.000e+00, 4.900e+01],
       [8.000e+00, 6.400e+01],
       [9.000e+00, 8.100e+01],
       [1.000e+01, 1.000e+02],
       [1.100e+01, 1.210e+02],
       [1.200e+01, 1.440e+02],
       [1.300e+01, 1.690e+02],
       [1.400e+01, 1.960e+02],
       [1.500e+01, 2.250e+02],
       [1.600e+01, 2.560e+02],
       [1.700e+01, 2.890e+02],
       [1.800e+01, 3.240e+02],
       [1.900e+01, 3.610e+02],
       [2.000e+01, 4.000e+02],
       [2.100e+01, 4.410e+02],
       [2.200e+01, 4.840e+02],
       [2.300e+01, 5.290e+02],
       [2.400e+01, 5.760e+02],
       [2.500e+01, 6.250e+02],
       [2.600e+01, 6.760e+02],
       [2.700e+01, 7.290e+02],
       [2.800e+01, 7.840e+02],
       [2.900e+01, 8.410e+02],
       [3.000e+01, 9.000e+02],
       [3.100e+01, 9.610e+02],
       [

In [21]:
y.shape

(100, 2)

In [22]:
y[0]

array([0., 0.])

In [23]:
y[1]

array([1., 1.])

In [24]:
data = np.recfromcsv('index.csv', delimiter=',', encoding='utf-8')
print(data)

[( 1,    1) ( 2,    4) ( 3,    9) ( 4,   16) ( 5,   25) ( 6,   36)
 ( 7,   49) ( 8,   64) ( 9,   81) (10,  100) (11,  121) (12,  144)
 (13,  169) (14,  196) (15,  225) (16,  256) (17,  289) (18,  324)
 (19,  361) (20,  400) (21,  441) (22,  484) (23,  529) (24,  576)
 (25,  625) (26,  676) (27,  729) (28,  784) (29,  841) (30,  900)
 (31,  961) (32, 1024) (33, 1089) (34, 1156) (35, 1225) (36, 1296)
 (37, 1369) (38, 1444) (39, 1521) (40, 1600) (41, 1681) (42, 1764)
 (43, 1849) (44, 1936) (45, 2025) (46, 2116) (47, 2209) (48, 2304)
 (49, 2401) (50, 2500) (51, 2601) (52, 2704) (53, 2809) (54, 2916)
 (55, 3025) (56, 3136) (57, 3249) (58, 3364) (59, 3481) (60, 3600)
 (61, 3721) (62, 3844) (63, 3969) (64, 4096) (65, 4225) (66, 4356)
 (67, 4489) (68, 4624) (69, 4761) (70, 4900) (71, 5041) (72, 5184)
 (73, 5329) (74, 5476) (75, 5625) (76, 5776) (77, 5929) (78, 6084)
 (79, 6241) (80, 6400) (81, 6561) (82, 6724) (83, 6889) (84, 7056)
 (85, 7225) (86, 7396) (87, 7569) (88, 7744) (89, 7921) (90, 8